# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-06 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20160806_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_name', models.CharField(max_length=255)),
                ('publication_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('review', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='release',
            name='catalog_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='release',
            name='credits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='format',
            field=models.CharField(choices=[('cd', 'Compact Disc'), ('cdr', 'Compact Disc-Recordable'), ('digital', 'Digital'), ('usb', 'USB / Flash Media'), ('vinyl', 'Vinyl Record'), ('cassette', 'Cassette Tape'), ('other', 'Other')], default='cd', max_length=255),
        ),
        migrations.AddField(
            model_name='release',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.Release'),
        ),
    ]
