# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-06 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20160806_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='published_date',
            new_name='release_date',
        ),
    ]
