# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-06 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20160806_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='embed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
