# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-04 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20160806_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='url',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='band',
        ),
        migrations.RemoveField(
            model_name='release',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='release',
            name='band',
        ),
        migrations.RemoveField(
            model_name='release',
            name='label',
        ),
        migrations.RemoveField(
            model_name='review',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='review',
            name='publication_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='release',
        ),
        migrations.AddField(
            model_name='artist',
            name='bandcamp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='bands',
            field=models.ManyToManyField(blank=True, to='catalog.Band'),
        ),
        migrations.AddField(
            model_name='artist',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='soundcloud',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='bandcamp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='soundcloud',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='artists',
            field=models.ManyToManyField(blank=True, to='catalog.Artist'),
        ),
        migrations.AddField(
            model_name='release',
            name='bandcamp_embed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='release',
            name='bandcamp_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='release',
            name='bands',
            field=models.ManyToManyField(blank=True, to='catalog.Band'),
        ),
        migrations.AddField(
            model_name='release',
            name='labels',
            field=models.ManyToManyField(blank=True, to='catalog.Label'),
        ),
        migrations.AddField(
            model_name='release',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='catalog.Review'),
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='publication',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
