# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-04 15:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20160904_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='embed',
        ),
    ]
